import { useEffect, useRef } from 'react';
import './ParticleText.css';

const rgb = h => { const s=h.replace('#','').trim(); if(!/^[0-9a-fA-F]{6}$/.test(s)) return null; return {r:parseInt(s.slice(0,2),16),g:parseInt(s.slice(2,4),16),b:parseInt(s.slice(4,6),16)}; };
const clamp=(v,a,b)=>Math.min(Math.max(v,a),b);
export default function ParticleText({text='[SEU NOME]',particleSize=2,density=4,color='#fff',highlightColor='#8b5cf6',scatter=180,gatherDuration=1600,stagger=420,pointerRepel=40,repelRadius=120,idleDrift=.7,trigger='mount',fontSize='clamp(3rem,12vw,8rem)',fontWeight=800,fontFamily='inherit',glow=true,className='',style={}}){
 const ref=useRef(null), canvas=useRef(null);
 useEffect(()=>{const box=ref.current,c=canvas.current;if(!box||!c)return;const ctx=c.getContext('2d');let parts=[],raf=0,w=0,h=0,dpr=1;let state={active:false,x:0,y:0,sx:0,sy:0};let reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 const rebuild=()=>{w=Math.floor(box.clientWidth);h=Math.floor(box.clientHeight);dpr=Math.min(devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const off=document.createElement('canvas'),o=off.getContext('2d');const cs=getComputedStyle(box);const family=fontFamily==='inherit'?cs.fontFamily:fontFamily;let size=96;if(typeof fontSize==='number'){size=fontSize}else{const probe=document.createElement('span');probe.textContent='M';probe.style.position='absolute';probe.style.visibility='hidden';probe.style.pointerEvents='none';probe.style.fontSize=fontSize;probe.style.fontWeight=String(fontWeight);probe.style.fontFamily=family;box.appendChild(probe);size=parseFloat(getComputedStyle(probe).fontSize)||96;probe.remove()}o.font=`${fontWeight} ${size}px ${family}`;let m=o.measureText(text);if(m.width>w*.9){size*=w*.9/m.width;o.font=`${fontWeight} ${size}px ${family}`;m=o.measureText(text)};const pad=Math.max(12,size*.08);off.width=Math.ceil(m.width+pad*2);off.height=Math.ceil(size*1.3+pad*2);o.font=`${fontWeight} ${size}px ${family}`;o.fillStyle='#fff';o.textBaseline='alphabetic';o.fillText(text,pad,pad+size);const data=o.getImageData(0,0,off.width,off.height).data;const targets=[];for(let y=0;y<off.height;y+=Math.max(2,density)){for(let x=0;x<off.width;x+=Math.max(2,density)){if(data[(y*off.width+x)*4+3]>40)targets.push({x:w/2-off.width/2+x,y:h/2-off.height/2+y})}};const max=Math.min(5200,Math.max(500,w*h/80));const step=Math.max(1,Math.ceil(targets.length/max));const base=rgb(color),hi=rgb(highlightColor);parts=targets.filter((_,i)=>i%step===0).map((t,i)=>{const seed=(Math.sin(i*12.9898)*43758.5453)%1;const s=(Math.abs(seed)+0.35)*scatter;return {tx:t.x,ty:t.y,x:reduced?t.x:t.x+Math.cos(i)*s,y:reduced?t.y:t.y+Math.sin(i)*s,seed:Math.abs(seed),depth:.5+Math.abs(seed)};});
 };
 const render=now=>{ctx.clearRect(0,0,w,h);const b=rgb(color),hi=rgb(highlightColor);ctx.shadowBlur=glow&&!reduced?particleSize*3:0;ctx.shadowColor=highlightColor;for(const p of parts){let x=p.tx,y=p.ty;if(!reduced&&idleDrift){x+=Math.sin(now*.001+p.seed*10)*idleDrift*p.depth;y+=Math.cos(now*.0008+p.seed*8)*idleDrift*p.depth}if(state.active&&!reduced){const dx=x-state.sx,dy=y-state.sy,d=Math.hypot(dx,dy);if(d>0&&d<repelRadius){const f=Math.pow(1-d/repelRadius,2)*pointerRepel;x+=dx/d*f;y+=dy/d*f}};const amount=clamp(x/Math.max(1,w)+(p.seed-.5)*.25,0,1);const col=b&&hi?`rgb(${Math.round(b.r+(hi.r-b.r)*amount)},${Math.round(b.g+(hi.g-b.g)*amount)},${Math.round(b.b+(hi.b-b.b)*amount)})`:color;ctx.fillStyle=col;ctx.fillRect(x-particleSize/2,y-particleSize/2,particleSize,particleSize)}raf=requestAnimationFrame(render)};
 const move=e=>{const r=c.getBoundingClientRect();state.active=true;state.sx=e.clientX-r.left;state.sy=e.clientY-r.top;if(trigger==='hover')rebuild()};const leave=()=>state.active=false;const ro=new ResizeObserver(rebuild);ro.observe(box);c.addEventListener('pointermove',move);c.addEventListener('pointerleave',leave);rebuild();raf=requestAnimationFrame(render);return()=>{cancelAnimationFrame(raf);ro.disconnect();c.removeEventListener('pointermove',move);c.removeEventListener('pointerleave',leave)}} ,[text,particleSize,density,color,highlightColor,scatter,pointerRepel,repelRadius,idleDrift,fontSize,fontWeight,fontFamily,glow,trigger,gatherDuration,stagger]);
 return <div ref={ref} className={`particle-text ${className}`} style={style} aria-label={text}><canvas ref={canvas} className="particle-text__canvas"/></div>;
}
